name: Wasm

on:
  push:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: mymindstorm/setup-emsdk@v14
    - name: Build
      run: |
        mkdir build
        cd build
        emcmake cmake ..
        emmake make
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasm-build-artifacts
        path: build
